apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: db-storage-claim
  containers:
    - name: temp-pod
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: "/pvc"
          name: mypvc